// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Models;

public partial class Context : DbContext
{
    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<L_Annexes> L_Annexes { get; set; }

    public virtual DbSet<L_LetterMain> L_LetterMain { get; set; }

    public virtual DbSet<L_Letter_Tags> L_Letter_Tags { get; set; }

    public virtual DbSet<L_Lines> L_Lines { get; set; }

    public virtual DbSet<L_Tags> L_Tags { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<L_Annexes>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_L_Upload");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.FileBinary).HasComment("文件二进制");
            entity.Property(e => e.FileName).HasComment("信函名称");
            entity.Property(e => e.FileSuffix).HasComment("文件后缀");
            entity.Property(e => e.Letter_Id).HasComment("信函ID");
            entity.Property(e => e.PhysicalAddress).HasComment("文件物理地址");

            entity.HasOne(d => d.Letter).WithMany(p => p.L_Annexes).HasConstraintName("FK_L_Annexes_L_LetterMain");
        });

        modelBuilder.Entity<L_LetterMain>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
            entity.Property(e => e.Virtual)
                .HasDefaultValueSql("((0))")
                .HasComment("在创建引用的时候，该引用是否为虚构; 虚构:true, 非虚构:false");
        });

        modelBuilder.Entity<L_Letter_Tags>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_L_Litter_Tags");

            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.Letter).WithMany(p => p.L_Letter_Tags).HasConstraintName("FK_L_Letter_Tags_L_LetterMain");

            entity.HasOne(d => d.Tags).WithMany(p => p.L_Letter_Tags)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_L_Letter_Tags_L_Tags");
        });

        modelBuilder.Entity<L_Lines>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");

            entity.HasOne(d => d.From).WithMany(p => p.L_LinesFrom)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_From_ID");

            entity.HasOne(d => d.To).WithMany(p => p.L_LinesTo).HasConstraintName("FK_To_ID");
        });

        modelBuilder.Entity<L_Tags>(entity =>
        {
            entity.Property(e => e.Id).HasDefaultValueSql("(newid())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}