// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models;

public partial class L_Annexes
{
    [Key]
    public Guid Id { get; set; }

    /// <summary>
    /// 信函ID
    /// </summary>
    public Guid Letter_Id { get; set; }

    /// <summary>
    /// 信函名称
    /// </summary>
    [Required]
    public string FileName { get; set; }

    /// <summary>
    /// 文件后缀
    /// </summary>
    [Required]
    [StringLength(50)]
    public string FileSuffix { get; set; }

    public double FileSize { get; set; }

    /// <summary>
    /// 文件物理地址
    /// </summary>
    [Required]
    public string PhysicalAddress { get; set; }

    /// <summary>
    /// 文件二进制
    /// </summary>
    public byte[] FileBinary { get; set; }

    [ForeignKey("Letter_Id")]
    [InverseProperty("L_Annexes")]
    public virtual L_LetterMain Letter { get; set; }
}