// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models;

public partial class L_Letter_Tags
{
    [Key]
    public Guid Id { get; set; }

    public Guid Letter_ID { get; set; }

    public Guid Tags_ID { get; set; }

    [ForeignKey("Letter_ID")]
    [InverseProperty("L_Letter_Tags")]
    public virtual L_LetterMain Letter { get; set; }

    [ForeignKey("Tags_ID")]
    [InverseProperty("L_Letter_Tags")]
    public virtual L_Tags Tags { get; set; }
}