// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models;

public partial class L_LetterMain
{
    [Key]
    public Guid Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    [Column(TypeName = "date")]
    public DateTime date { get; set; }

    public string NO_AlWaha { get; set; }

    public string NO_MDOC { get; set; }

    [StringLength(20)]
    public string type { get; set; }

    /// <summary>
    /// 在创建引用的时候，该引用是否为虚构; 虚构:true, 非虚构:false
    /// </summary>
    public bool? Virtual { get; set; }

    [InverseProperty("Letter")]
    public virtual ICollection<L_Annexes> L_Annexes { get; set; } = new List<L_Annexes>();

    [InverseProperty("Letter")]
    public virtual ICollection<L_Letter_Tags> L_Letter_Tags { get; set; } = new List<L_Letter_Tags>();

    [InverseProperty("From")]
    public virtual ICollection<L_Lines> L_LinesFrom { get; set; } = new List<L_Lines>();

    [InverseProperty("To")]
    public virtual ICollection<L_Lines> L_LinesTo { get; set; } = new List<L_Lines>();
}