// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models;

public partial class L_Lines
{
    [Key]
    public Guid Id { get; set; }

    public Guid From_ID { get; set; }

    public Guid To_ID { get; set; }

    [Required]
    [StringLength(50)]
    public string Text { get; set; }

    [ForeignKey("From_ID")]
    [InverseProperty("L_LinesFrom")]
    public virtual L_LetterMain From { get; set; }

    [ForeignKey("To_ID")]
    [InverseProperty("L_LinesTo")]
    public virtual L_LetterMain To { get; set; }
}