// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Models;

public partial class L_Tags
{
    [Key]
    public Guid Id { get; set; }

    [Required]
    public string Title { get; set; }

    [InverseProperty("Tags")]
    public virtual ICollection<L_Letter_Tags> L_Letter_Tags { get; set; } = new List<L_Letter_Tags>();
}